### PR TITLE
Fix package.json: license, description

### LINKED ISSUE #17: License file update needed
See: http://npm1k.org/

### PR DESCRIPTION
**Pull request by bajtos**
- Change the license property to use the new SPDX expression format.
- Update the description to mention that we can build data URIs too.

Close #17

/to @rmg please review
/cc @hildjj

### CODE REVIEW

**Comment by rmg** [comment]
The original license is MIT, was the change to Artistic-2.0 intentional?

**Comment by bajtos** [comment]
Good catch! The license change was not intentional.

**Comment by bajtos** [comment]
@rmg fixed, LGTY now?

**Comment by hildjj** [comment]
LGTM

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
LGTM.

**Pull request merged**
