### PR TITLE
Add a binary

### PR DESCRIPTION
**Pull request by hildjj**
decode: data-uri data:foo
encode: data-uri filename
decode: data-uri < filename-containing-data-starting-with-data:
encode: data-uri < filename

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @hildjj, thank you for the pull request. I am happy to add the `encode` function, though I am not sure about the CLI script. Without CLI, this module is super small and light with almost no dependencies. The CLI tools add `mime` (and possibly argv processor later) and thus imposing extra dependencies on users that don't care about CLI interface.

I am proposing to remove the CLI script from this patch and move it to a standalone module (a new project under your GitHub name).

Thoughts?

**Comment by hildjj** [comment]
I can live with that, if you link to the new cli module in your README.

**Comment by bajtos** [comment]
> I can live with that, if you link to the new cli module in your README.

Sounds good, just sent a pull request to add the link to README.

**Pull request closed without merging**
