### PR TITLE
Add encode

### PR DESCRIPTION
**Pull request by hildjj**
I signed the CLA, added encode, tests, and updated the README.md.  Let me know if  you want other modifications before accepting.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by hildjj** [comment]
Note: the build is failing for HEAD; the build failure on this patch is just the same issue. I would suggest changing the build targets in .travis.yml to be 0.10, 0.12, removing 0.8 and 0.11.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
> Note: the build is failing for HEAD; the build failure on this patch is just the same issue. I would suggest changing the build targets in .travis.yml to be 0.10, 0.12, removing 0.8 and 0.11.

I'll address that in https://github.com/strongloop/strong-data-uri/pull/9. I don't want to drop support for 0.8 as that would be a breaking change.

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Comment by bajtos** [comment]
Released as `strong-data-uri@0.2.0`.

**Pull request merged**
